#!/usr/bin/env bash

# Copyright 2022 Antrea Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

COUNT_DOC_DIFF=$(git diff --name-only --staged '*.md' | wc -l)
COUNT_GOLANG_DIFF=$(git diff --name-only --staged '*.go' | wc -l)

if [ "$COUNT_DOC_DIFF" -gt 0 ]
then
  make verify
  MAKE_VERIFY=$?

  if [ "$MAKE_VERIFY" != 0 ]
  then
     echo "The command: 'make verify' failed! Please fix and try again!"
     exit 1
  fi
fi

if [ "$COUNT_GOLANG_DIFF" -gt 0 ]
then
  make golangci
  MAKE_GOLANGCI=$?

  if [ "$MAKE_GOLANGCI" != 0 ]
  then
     echo "The command: 'make golangci' failed! Please fix and try again!"
     exit 1
  fi
fi
