FROM python:rc-alpine3.10

LABEL maintainer="Antrea <projectantrea-dev@googlegroups.com>"
LABEL description="A Docker image based on Alpine with pyhton and wget"

RUN apk add --no-cache ca-certificates wget && update-ca-certificates
