// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/antrea/v2/pkg/agent/proxy (interfaces: ProxyQuerier)
//
// Generated by this command:
//
//	mockgen -copyright_file hack/boilerplate/license_header.raw.txt -destination pkg/agent/proxy/testing/mock_proxy.go -package testing antrea.io/antrea/v2/pkg/agent/proxy ProxyQuerier
//

// Package testing is a generated GoMock package.
package testing

import (
	reflect "reflect"

	openflow "antrea.io/antrea/v2/pkg/ovs/openflow"
	proxy "antrea.io/antrea/v2/third_party/proxy"
	gomock "go.uber.org/mock/gomock"
)

// MockProxyQuerier is a mock of ProxyQuerier interface.
type MockProxyQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockProxyQuerierMockRecorder
	isgomock struct{}
}

// MockProxyQuerierMockRecorder is the mock recorder for MockProxyQuerier.
type MockProxyQuerierMockRecorder struct {
	mock *MockProxyQuerier
}

// NewMockProxyQuerier creates a new mock instance.
func NewMockProxyQuerier(ctrl *gomock.Controller) *MockProxyQuerier {
	mock := &MockProxyQuerier{ctrl: ctrl}
	mock.recorder = &MockProxyQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyQuerier) EXPECT() *MockProxyQuerierMockRecorder {
	return m.recorder
}

// GetServiceByIP mocks base method.
func (m *MockProxyQuerier) GetServiceByIP(serviceStr string) (proxy.ServicePortName, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceByIP", serviceStr)
	ret0, _ := ret[0].(proxy.ServicePortName)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetServiceByIP indicates an expected call of GetServiceByIP.
func (mr *MockProxyQuerierMockRecorder) GetServiceByIP(serviceStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceByIP", reflect.TypeOf((*MockProxyQuerier)(nil).GetServiceByIP), serviceStr)
}

// GetServiceFlowKeys mocks base method.
func (m *MockProxyQuerier) GetServiceFlowKeys(serviceName, namespace string) ([]string, []openflow.GroupIDType, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceFlowKeys", serviceName, namespace)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]openflow.GroupIDType)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetServiceFlowKeys indicates an expected call of GetServiceFlowKeys.
func (mr *MockProxyQuerierMockRecorder) GetServiceFlowKeys(serviceName, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceFlowKeys", reflect.TypeOf((*MockProxyQuerier)(nil).GetServiceFlowKeys), serviceName, namespace)
}
