version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - gosec
    - govet
    - loggercheck
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G115
    misspell:
      ignore-rules:
        - creater
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: unreachable-code
        - name: errorf
        - name: range
        - name: superfluous-else
        - name: var-declaration
        - name: duplicated-imports
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - antrea.io/antrea
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
