# golangci-lint configuration used for CI
run:
  tests: true
  timeout: 10m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs-use-default: true

linters-settings:
  goimports:
    local-prefixes: github.com/vmware-tanzu/antrea

linters:
  disable-all: true
  enable:
    - misspell
    - gofmt
    - deadcode
    - staticcheck
    - gosec
    - goimports
    - vet
