# golangci-lint configuration used for CI
version: "2"
run:
  tests: true
  timeout: 15m
linters:
  default: none
  enable:
    - gosec
    - govet
    - loggercheck
    - misspell
    - revive
    - staticcheck
    - unused
    - tagliatelle
  settings:
    gosec:
      excludes:
       # At the time of writing this, the G115 rule is not even part of an
       # official release of gosec. This rule causes a lot of errors to be
       # reported in the codebase. While some of the reported errors should be
       # addressed, a lot can also be ignored and there are also some clear false
       # positives that should not be flagged by gosec in the first place (see
       # https://github.com/securego/gosec/issues/1187). We will re-enable this
       # rule in the future when it becomes more accurate.
        - G115 # Potential integer overflow when converting between integer types
    misspell:
      ignore-rules:
        - creater
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: unreachable-code
        - name: errorf
        - name: range
        - name: superfluous-else
        - name: var-declaration
        - name: duplicated-imports

    tagliatelle:
      case:
          rules:
            json: goCamel
            yaml: goCamel
          overrides:  

            - pkg: test
              ignore: true
            #Format for ignored-fields comments - current : expected
            - pkg: pkg/ovs/ovsconfig
              ignored-fields:
                - DatapathType # datapath_type : datapathType
                - ExternalIDs # external_ids : externalIDs
                - McastSnoopingEnable # mcast_snooping_enable : mcastSnoopingEnable
                - OFPortRequest # ofport_request : ofPortRequest
                
            - pkg: pkg/flowaggregator/apis
              ignored-fields:
                - WithIPFIXExporter # withIPFIXExporter : withIpfixExporter

            - pkg: pkg/config/flowaggregator
              ignored-fields:
                - MaxIPFIXMsgSize # maxIPFIXMsgSize : maxIpfixMsgSize
            
            - pkg: pkg/config/controller
              ignored-fields:
                - ClientCAFile # clientCAFile : clientCaFile
                - ClusterCIDRs # clusterCIDRs : clusterCidRs
                - EnableNodeIPAM # enableNodeIPAM : enableNodeIpam
                - IPsecCSRSignerConfig # ipsecCSRSigner : iPsecCsrSignerConfig
                - NodeCIDRMaskSizeIPv4 # nodeCIDRMaskSizeIPv4 : nodeCidrMaskSizeIPv4
                - NodeCIDRMaskSizeIPv6 # nodeCIDRMaskSizeIPv6 : nodeCidrMaskSizeIPv6
                - NodeIPAM # nodeIPAM : nodeIpam
                - SelfSignedCA # selfSignedCA : selfSignedCa
                - ServiceCIDR # serviceCIDR : serviceCidr
                - ServiceCIDRv6 # serviceCIDRv6 : serviceCidRv6
            
            - pkg: pkg/config/agent
              ignored-fields:
                - ClusterMembershipPort # clusterPort : clusterMembershipPort
                - DefaultMTU # defaultMTU : defaultMtu
                - DisableTXChecksumOffload # disableTXChecksumOffload : disableTxChecksumOffload
                - ExceptCIDRs # exceptCIDRs : exceptCidRs
                - IPsec # ipsec : iPsec
                - NoSNAT # noSNAT : noSnat
                - ServiceCIDR # serviceCIDR : serviceCidr
                - ServiceCIDRv6 # serviceCIDRv6 : serviceCidRv6
                - TransportInterfaceCIDRs # transportInterfaceCIDRs : transportInterfaceCidR

            - pkg: pkg/apiserver/apis
              ignored-fields:
                - AppliedPolicies # policies : appliedPolicies
                - EgressDstRules # gressdstrules : egressDstRules
                - IngressSrcRules # ingresssrcrules : ingressSrcRules
                - PolicyRef # policyref' want 'policyRef
                - RuleIndex # ruleindex : ruleIndex
            
            - pkg: pkg/apis/system
              ignored-fields:
                - ObjectMeta # metadata : objectMeta
            
            - pkg: pkg/apis/stats
              ignored-fields:
                - LastMeasuredRTTNanoseconds # lastMeasuredRTTNanoseconds : lastMeasuredRttNanoseconds
                - ListMeta # metadata : listMeta
                - ObjectMeta # metadata : objectMeta

            - pkg: pkg/apis/crd
              ignored-fields:
                - APICABundle # apiCABundle : apicaBundle
                - DstMAC # dstMAC : dstMac
                - IPv6Header # 'ipv6Header : iPv6Header'
                - ListMeta # metadata : listMeta
                - LocalASN # localASN : localAsn
                - MemberASNs # memberASNs : memberAsNs
                - ObjectMeta # metadata : objectMeta
            
            - pkg: pkg/apis/controlplane
              ignored-fields:
                - ListMeta # metadata : listMeta
                - ObjectMeta # metadata : objectMeta
            
            - pkg: pkg/antctl/raw
              ignored-fields:
                - IPv6Header # 'ipv6Header : iPv6Header'
                - NodeResults # results : nodeResults
                - TransportHeader # tranportHeader : transportHeader
            
            - pkg: pkg/agent/flowexporter
              ignored-fields:
                - ContentLength # length : contentLength
                - ContentType # http_content_type : contentType
                - DestIP # dest_ip : destIP
                - DestPort # dest_port : destPort
                - EventType # event_type : eventType
                - FlowID # flow_id : flowID
                - InInterface # in_iface : inInterface
                - Method # http_method : method
                - SrcIP # src_ip : srcIP
                - SrcPort # src_port : srcPort
                - TxID # tx_id : txID
                - UserAgent # http_user_agent : userAgent
            
            - pkg: pkg/agent/cniserver
              ignored-fields:
                - IPPools # ippools : ipPools
                - Nameservers # servers : nameservers
                - RawPrevResult # prevResult : rawPrevResult
                - Search # searches : search
            
            - pkg: pkg/agent/apis
              ignored-fields:
                - BGPPolicyName # name' want 'bgpPolicyName
                - IPs # ips : iPs
                - LocalASN # localASN : localAsn
                - MemberASNs # memberASNs : memberAsNs
                - Nameservers # servers : nameservers
                - PodName # name' want 'podName
            
            - pkg: multicluster/apis/multicluster
              ignored-fields:
                - ListMeta # metadata : listMeta
                - ObjectMeta # metadata : objectMeta
                - PodCIDRs # podCIDRs : podCidRs
                - ServiceCIDR # serviceCIDR : serviceCidr
            
            - pkg: pkg/agent/util
              ignored-fields:
                - Extensions # Extensions : extensions
                - ExtensionID # Id : extensionID

          use-field-name: true

  exclusions:
    presets:
      - legacy
      - common-false-positives
    paths:
      - ^third_party/.*
    rules:
      - linters:
          - staticcheck
        # ST1005: error strings must be capitalized
        # QF1008: unneccessary use of embedded struct name before field e.g:
        #   ClusterNetworkPolicy.Metadata.Name vs ClusterNetworkPolicy.Name
        text: "(ST1005:|QF1008:)"
      - linters:
          - staticcheck
        text: "SA1019: (v1|corev1).Endpoints is deprecated"
      - linters:
          - staticcheck
        text: "SA1019: (v1|corev1).EndpointSubset is deprecated"
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - antrea.io/antrea
  exclusions:
    paths:
      - ^third_party/.*

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
