# golangci-lint configuration used for CI
version: "2"
run:
  tests: true
  timeout: 15m
linters:
  default: none
  enable:
    - gosec
    - govet
    - loggercheck
    - misspell
    - revive
    - staticcheck
    - unused
    - tagliatelle
  settings:
    gosec:
      excludes:
       # At the time of writing this, the G115 rule is not even part of an
       # official release of gosec. This rule causes a lot of errors to be
       # reported in the codebase. While some of the reported errors should be
       # addressed, a lot can also be ignored and there are also some clear false
       # positives that should not be flagged by gosec in the first place (see
       # https://github.com/securego/gosec/issues/1187). We will re-enable this
       # rule in the future when it becomes more accurate.
        - G115 # Potential integer overflow when converting between integer types
    misspell:
      ignore-rules:
        - creater
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: unreachable-code
        - name: errorf
        - name: range
        - name: superfluous-else
        - name: var-declaration
        - name: duplicated-imports
    tagliatelle:
      case:
          rules:
            json: goCamel
            yaml: goCamel
          ignored-fields: # Current: Expected
            - APICABundle # apiCABundle : apicaBundle
            - AppliedPolicies # policies : appliedPolicies
            - AppProtocol # app_proto : appProtocol
            - BGPPolicyName # name' want 'bgpPolicyName
            - BrName #ovsBinding : brName
            - ClientCAFile # clientCAFile : clientCaFile
            - ClusterCIDRs # clusterCIDRs : clusterCidRs
            - ClusterIDs # clusterID : clusterIDs
            - ClusterInfo # clusterinfo : clusterInfo
            - ClusterNetworkPolicy # clusternetworkpolicy : clusterNetworkPolicy
            - ContentLength # length : contentLength
            - ContentType # http_content_type : contentType
            # - AppliedPolicies
            - ClusterMembershipPort # clusterPort : clusterMembershipPort
            - DatapathType # datapath_type : datapathType
            - DestIP # dest_ip : destIP
            - DestPort # dest_port : destPort
            - DefaultMTU # defaultMTU : defaultMtu
            - DisableTXChecksumOffload # disableTXChecksumOffload : disableTxChecksumOffload
            - DstMAC # dstMAC : dstMac
            - EgressDstRules # gressdstrules : egressDstRules
            - EnableNodeIPAM # enableNodeIPAM : enableNodeIpam
            - EventType # event_type : eventType
            - ExceptCIDRs # exceptCIDRs : exceptCidRs
            - ExtensionID # Id : extensionID
            - Extensions # Extensions : extensions
            - ExternalEntity # externalentity : externalEntity
            - ExternalEntitySpec # externalentityspec : externalEntitySpec
            - ExternalIds # external_ids : externalIds
            - ExternalIDs # external_ids : externalIDs
            - FlowID # flow_id : flowID
            - FQDNs # fqdns : fqdNs
            - IngressSrcRules # ingresssrcrules : ingressSrcRules
            - InInterface # in_iface : inInterface
            - IPPools # ippools : ipPools
            - IPs # ips : iPs
            - IPsec # ipsec : iPsec
            - IPsecCSRSignerConfig # ipsecCSRSigner : iPsecCsrSignerConfig
            - IPv6Header # 'ipv6Header : iPv6Header'
            - LastMeasuredRTTNanoseconds # lastMeasuredRTTNanoseconds : lastMeasuredRttNanoseconds
            - ListMeta # metadata : listMeta
            - LocalASN # localASN : localAsn
            - MaxIPFIXMsgSize # maxIPFIXMsgSize : maxIpfixMsgSize
            - McastSnoopingEnable # mcast_snooping_enable : mcastSnoopingEnable
            - MemberASNs # memberASNs : memberAsNs
            - Method # http_method : method
            - Nameservers # servers : nameservers
            - NodeCIDRMaskSizeIPv4 # nodeCIDRMaskSizeIPv4 : nodeCidrMaskSizeIPv4
            - NodeCIDRMaskSizeIPv6 # nodeCIDRMaskSizeIPv6 : nodeCidrMaskSizeIPv6
            - NodeIPAM # nodeIPAM : nodeIpam
            - NodeResults # results : nodeResults
            - NoSNAT # noSNAT : noSnat
            - ObjectMeta # metadata : objectMeta
            - OFPortRequest # ofport_request : ofPortRequest
            - PacketBytes # packet : packetBytes
            - PodCIDRs # podCIDRs : podCidRs
            - PodName # name' want 'podName
            - PolicyRef # policyref' want 'policyRef
            - Port # http_port : port
            - Protocol # proto : protocol
            - RawPrevResult # prevResult : rawPrevResult
            - RuleIndex # ruleindex : ruleIndex
            - Search # searches : search
            - SelfSignedCA # selfSignedCA : selfSignedCa
            - ServiceCIDR # serviceCIDR : serviceCidr
            - ServiceCIDRv6 # serviceCIDRv6 : serviceCidRv6
            - SrcIP # src_ip : srcIP
            - SrcPort # src_port : srcPort
            - TransportInterfaceCIDRs # transportInterfaceCIDRs : transportInterfaceCidR
            - TransportHeader # tranportHeader : transportHeader
            - TxID # tx_id : txID
            - UserAgent # http_user_agent : userAgent
            - WithIPFIXExporter # withIPFIXExporter : withIpfixExporter
            
          use-field-name: true
  exclusions:
    presets:
      - legacy
      - common-false-positives
    paths:
      - ^third_party/.*
    rules:
      - linters:
          - staticcheck
        # ST1005: error strings must be capitalized
        # QF1008: unneccessary use of embedded struct name before field e.g:
        #   ClusterNetworkPolicy.Metadata.Name vs ClusterNetworkPolicy.Name
        text: "(ST1005:|QF1008:)"
      - linters:
          - staticcheck
        text: "SA1019: (v1|corev1).Endpoints is deprecated"
      - linters:
          - staticcheck
        text: "SA1019: (v1|corev1).EndpointSubset is deprecated"
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - antrea.io/antrea
  exclusions:
    paths:
      - ^third_party/.*

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
