# golangci-lint configuration used to run golint only (with all warnings enabled)
run:
  tests: true
  timeout: 5m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs-use-default: true

issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - golint
