codecov:
  token: a2b1c854-8627-4747-89cb-c312da33227d
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "0...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1
