codecov:
  branch: main
  require_ci_to_pass: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1
  show_carryforward_flags: true

github_checks:
  annotations: true

coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        only_pulls: true
        flags:
          - unit-tests
    project:
      default:
        target: auto
      antrea-unit-tests:
        target: auto
        flags:
          - unit-tests
      antrea-integration-tests:
        target: auto
        flags:
          - integration-tests
      antrea-e2e-tests:
        target: auto
        flags:
          - e2e-tests
      antrea-kind-e2e-tests:
        target: auto
        flags:
          - kind-e2e-tests

flags:
  unit-tests:
    carryforward: true
  integration-tests:
    carryforward: true
  e2e-tests:
    carryforward: true
  kind-e2e-tests:
    carryforward: true

ignore:
  - "**/testing/*.go"
  - "**/mock_*.go"
  - "**/*generate*.go"
  - "pkg/client"
  - "**/pkg/client"
  - "**/*.pb.go"
  - "third_party"
  - "bincover_run_main_test*"
