codecov:
  branch: main
  require_ci_to_pass: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: auto
      antrea-unit-tests:
        target: auto
        flags:
          - unit-tests
      antrea-integration-tests:
        target: auto
        flags:
          - integration-tests
      antrea-e2e-tests:
        target: auto
        flags:
          - e2e-tests
      antrea-kind-e2e-tests:
        target: auto
        flags:
          - kind-e2e-tests
      antrea-mc-integration-tests:
        target: auto
        flags:
          - mc-integration-tests

ignore:
  - "**/testing/mock_*.go"
  - "**/mock_*.go"
  - "**/*generate*.go"
  - "pkg/client"
  - "**/pkg/client"
  - "**/*.pb.go"
  - "third_party"
