codecov:
  branch: main
  require_ci_to_pass: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: no
  after_n_builds: 1
  show_carryforward_flags: false

coverage:
  status:
    project:
      default:
        target: auto
      antrea-unit-tests:
        target: auto
        flags:
          - unit-tests

flag_management:
  default_rules:
    carryforward: false

ignore:
  - "**/testing/mock_*.go"
  - "**/mock_*.go"
  - "**/*generate*.go"
  - "pkg/client"
  - "**/pkg/client"
  - "**/*.pb.go"
  - "third_party"
