codecov:
  branch: main
  require_ci_to_pass: no

comment: false
#  layout: "reach,diff,flags,tree"
#  behavior: default
#  require_changes: no
#  require_base: no
#  require_head: no
#  after_n_builds: 2
#  show_carryforward_flags: false

github_checks:
  annotations: true

coverage:
  status:
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        only_pulls: true
        flags:
          - unit-tests
    project:
      default:
        target: auto
      antrea-unit-tests:
        target: auto
        flags:
          - unit-tests

flag_management:
  default_rules:
    carryforward: false

ignore:
  - "**/testing/*.go"
  - "**/mock_*.go"
  - "**/*generate*.go"
  - "pkg/client"
  - "**/pkg/client"
  - "**/*.pb.go"
  - "third_party"
  - "bincover_run_main_test*"
