apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  namespace: lfx-mentorship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
        - name: toolbox
          image: antrea/toolbox:1.6