apiVersion: apps/v1
kind: Deployment
metadata:
  name: antrea-toolbox
  namespace: lfx-mentorship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: antrea-toolbox
        image: antrea/toolbox:1.6