[build]
  base = "site/"
  command = "hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.73.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.73.0"
