// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "antrea.io/antrea/pkg/apis/crd/v1alpha1"
	crdv1alpha1 "antrea.io/antrea/pkg/client/clientset/versioned/typed/crd/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeFlowExporterTargets implements FlowExporterTargetInterface
type fakeFlowExporterTargets struct {
	*gentype.FakeClientWithList[*v1alpha1.FlowExporterTarget, *v1alpha1.FlowExporterTargetList]
	Fake *FakeCrdV1alpha1
}

func newFakeFlowExporterTargets(fake *FakeCrdV1alpha1) crdv1alpha1.FlowExporterTargetInterface {
	return &fakeFlowExporterTargets{
		gentype.NewFakeClientWithList[*v1alpha1.FlowExporterTarget, *v1alpha1.FlowExporterTargetList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("flowexportertargets"),
			v1alpha1.SchemeGroupVersion.WithKind("FlowExporterTarget"),
			func() *v1alpha1.FlowExporterTarget { return &v1alpha1.FlowExporterTarget{} },
			func() *v1alpha1.FlowExporterTargetList { return &v1alpha1.FlowExporterTargetList{} },
			func(dst, src *v1alpha1.FlowExporterTargetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.FlowExporterTargetList) []*v1alpha1.FlowExporterTarget {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.FlowExporterTargetList, items []*v1alpha1.FlowExporterTarget) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
