// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "antrea.io/antrea/v2/pkg/apis/system/v1beta1"
	systemv1beta1 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/system/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSupportBundles implements SupportBundleInterface
type fakeSupportBundles struct {
	*gentype.FakeClient[*v1beta1.SupportBundle]
	Fake *FakeSystemV1beta1
}

func newFakeSupportBundles(fake *FakeSystemV1beta1) systemv1beta1.SupportBundleInterface {
	return &fakeSupportBundles{
		gentype.NewFakeClient[*v1beta1.SupportBundle](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("supportbundles"),
			v1beta1.SchemeGroupVersion.WithKind("SupportBundle"),
			func() *v1beta1.SupportBundle { return &v1beta1.SupportBundle{} },
		),
		fake,
	}
}
