apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplepod
  labels:
    environment: antrea-multus-demo
    app: samplepod
spec:
  replicas: 6
  selector:
    matchLabels:
      environment: antrea-multus-demo
      app: samplepod
  template:
    metadata:
      labels:
        environment: antrea-multus-demo
        app: samplepod
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      containers:
      - name: samplepod
        command: ["/bin/bash", "-c", "PID=; trap 'kill $PID' TERM INT; sleep infinity & PID=$!; wait $PID"]
        image: antoninbas/toolbox:latest
      nodeSelector:
        kubernetes.io/os: linux
