apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
spec:
  template:
    spec:
      containers:
        - command:
            - /antrea-mc-controller
            - member
          name: antrea-mc-controller
