apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  name: vmemberclusterannounce.kb.io
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kube-system
