apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  name: vmemberclusterannounce.kb.io
  $patch: delete
- admissionReviewVersions:
  name: vresourceexport.kb.io
  $patch: delete
- admissionReviewVersions:
  name: vresourceimport.kb.io
  $patch: delete
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  name: mresourceexport.kb.io
  $patch: delete
- admissionReviewVersions:
  name: mresourceimport.kb.io
  $patch: delete
- admissionReviewVersions:
  - v1
  - v1beta1
  name: mclusterclaim.kb.io
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kube-system
- admissionReviewVersions:
  - v1
  - v1beta1
  name: mclusterset.kb.io
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kube-system
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  name: vclusterclaim.kb.io
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kube-system
- admissionReviewVersions:
  - v1
  - v1beta1
  name: vclusterset.kb.io
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kube-system
