//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by openapi-gen. DO NOT EDIT.

package v1beta1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AgentCondition) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.AgentCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AntreaAgentInfo) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.AntreaAgentInfo"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AntreaAgentInfoList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.AntreaAgentInfoList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AntreaControllerInfo) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.AntreaControllerInfo"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AntreaControllerInfoList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.AntreaControllerInfoList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppliedTo) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.AppliedTo"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Bandwidth) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Bandwidth"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterGroup) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ClusterGroup"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterGroupList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ClusterGroupList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterNetworkPolicy) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ClusterNetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterNetworkPolicyList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ClusterNetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClusterNetworkPolicySpec) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ClusterNetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ControllerCondition) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ControllerCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Destination) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Destination"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Egress) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Egress"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressCondition) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.EgressCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.EgressList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressSpec) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.EgressSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EgressStatus) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.EgressStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExternalIPPool) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ExternalIPPool"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExternalIPPoolList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ExternalIPPoolList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExternalIPPoolSpec) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ExternalIPPoolSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ExternalIPPoolStatus) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ExternalIPPoolStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Group) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Group"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GroupCondition) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.GroupCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GroupList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.GroupList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GroupSpec) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.GroupSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GroupStatus) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.GroupStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPProtocol) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.HTTPProtocol"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ICMPEchoRequestHeader) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ICMPEchoRequestHeader"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ICMPProtocol) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.ICMPProtocol"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IGMPProtocol) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IGMPProtocol"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAddressOwner) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPAddressOwner"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAddressState) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPAddressState"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPBlock) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPBlock"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPHeader) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPHeader"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPool) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPPool"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPPoolList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolSpec) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPPoolSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolStatus) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPPoolStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolUsage) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPPoolUsage"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPRange) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPRange"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPv6Header) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.IPv6Header"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in L7Protocol) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.L7Protocol"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NamespacedName) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NamespacedName"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInfo) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkInfo"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicy) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyCondition) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicyCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyControllerInfo) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicyControllerInfo"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyPeer) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicyPeer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyPort) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicyPort"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyProtocol) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicyProtocol"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicySpec) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkPolicyStatus) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NetworkPolicyStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NodeResult) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.NodeResult"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OVSInfo) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.OVSInfo"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Observation) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Observation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Packet) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Packet"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PeerNamespaces) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.PeerNamespaces"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PeerService) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.PeerService"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PodOwner) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.PodOwner"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Rule) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Rule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Source) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Source"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StatefulSetOwner) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.StatefulSetOwner"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SubnetInfo) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.SubnetInfo"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TCPHeader) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.TCPHeader"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TLSProtocol) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.TLSProtocol"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Tier) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Tier"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TierList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.TierList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TierSpec) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.TierSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Traceflow) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.Traceflow"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TraceflowList) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.TraceflowList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TraceflowSpec) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.TraceflowSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TraceflowStatus) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.TraceflowStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in TransportHeader) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.TransportHeader"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UDPHeader) OpenAPIModelName() string {
	return "io.antrea.crd.v1beta1.UDPHeader"
}
