// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	multiclusterv1alpha1 "antrea.io/antrea/v2/multicluster/apis/multicluster/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterSetLister helps list ClusterSets.
// All objects returned here must be treated as read-only.
type ClusterSetLister interface {
	// List lists all ClusterSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiclusterv1alpha1.ClusterSet, err error)
	// ClusterSets returns an object that can list and get ClusterSets.
	ClusterSets(namespace string) ClusterSetNamespaceLister
	ClusterSetListerExpansion
}

// clusterSetLister implements the ClusterSetLister interface.
type clusterSetLister struct {
	listers.ResourceIndexer[*multiclusterv1alpha1.ClusterSet]
}

// NewClusterSetLister returns a new ClusterSetLister.
func NewClusterSetLister(indexer cache.Indexer) ClusterSetLister {
	return &clusterSetLister{listers.New[*multiclusterv1alpha1.ClusterSet](indexer, multiclusterv1alpha1.Resource("clusterset"))}
}

// ClusterSets returns an object that can list and get ClusterSets.
func (s *clusterSetLister) ClusterSets(namespace string) ClusterSetNamespaceLister {
	return clusterSetNamespaceLister{listers.NewNamespaced[*multiclusterv1alpha1.ClusterSet](s.ResourceIndexer, namespace)}
}

// ClusterSetNamespaceLister helps list and get ClusterSets.
// All objects returned here must be treated as read-only.
type ClusterSetNamespaceLister interface {
	// List lists all ClusterSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*multiclusterv1alpha1.ClusterSet, err error)
	// Get retrieves the ClusterSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*multiclusterv1alpha1.ClusterSet, error)
	ClusterSetNamespaceListerExpansion
}

// clusterSetNamespaceLister implements the ClusterSetNamespaceLister
// interface.
type clusterSetNamespaceLister struct {
	listers.ResourceIndexer[*multiclusterv1alpha1.ClusterSet]
}
