// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware-tanzu/antrea/pkg/monitor (interfaces: ControllerQuerier)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
	reflect "reflect"
)

// MockControllerQuerier is a mock of ControllerQuerier interface
type MockControllerQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockControllerQuerierMockRecorder
}

// MockControllerQuerierMockRecorder is the mock recorder for MockControllerQuerier
type MockControllerQuerierMockRecorder struct {
	mock *MockControllerQuerier
}

// NewMockControllerQuerier creates a new mock instance
func NewMockControllerQuerier(ctrl *gomock.Controller) *MockControllerQuerier {
	mock := &MockControllerQuerier{ctrl: ctrl}
	mock.recorder = &MockControllerQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockControllerQuerier) EXPECT() *MockControllerQuerierMockRecorder {
	return m.recorder
}

// GetSelfNode mocks base method
func (m *MockControllerQuerier) GetSelfNode() v1.ObjectReference {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelfNode")
	ret0, _ := ret[0].(v1.ObjectReference)
	return ret0
}

// GetSelfNode indicates an expected call of GetSelfNode
func (mr *MockControllerQuerierMockRecorder) GetSelfNode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelfNode", reflect.TypeOf((*MockControllerQuerier)(nil).GetSelfNode))
}

// GetSelfPod mocks base method
func (m *MockControllerQuerier) GetSelfPod() v1.ObjectReference {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelfPod")
	ret0, _ := ret[0].(v1.ObjectReference)
	return ret0
}

// GetSelfPod indicates an expected call of GetSelfPod
func (mr *MockControllerQuerierMockRecorder) GetSelfPod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelfPod", reflect.TypeOf((*MockControllerQuerier)(nil).GetSelfPod))
}

// GetService mocks base method
func (m *MockControllerQuerier) GetService() v1.ObjectReference {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService")
	ret0, _ := ret[0].(v1.ObjectReference)
	return ret0
}

// GetService indicates an expected call of GetService
func (mr *MockControllerQuerierMockRecorder) GetService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockControllerQuerier)(nil).GetService))
}

// GetVersion mocks base method
func (m *MockControllerQuerier) GetVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetVersion indicates an expected call of GetVersion
func (mr *MockControllerQuerierMockRecorder) GetVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockControllerQuerier)(nil).GetVersion))
}
