// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "antrea.io/antrea/v2/pkg/apis/controlplane/v1beta2"
	controlplanev1beta2 "antrea.io/antrea/v2/pkg/client/clientset/versioned/typed/controlplane/v1beta2"
	gentype "k8s.io/client-go/gentype"
)

// fakeSupportBundleCollections implements SupportBundleCollectionInterface
type fakeSupportBundleCollections struct {
	*gentype.FakeClientWithList[*v1beta2.SupportBundleCollection, *v1beta2.SupportBundleCollectionList]
	Fake *FakeControlplaneV1beta2
}

func newFakeSupportBundleCollections(fake *FakeControlplaneV1beta2) controlplanev1beta2.SupportBundleCollectionInterface {
	return &fakeSupportBundleCollections{
		gentype.NewFakeClientWithList[*v1beta2.SupportBundleCollection, *v1beta2.SupportBundleCollectionList](
			fake.Fake,
			"",
			v1beta2.SchemeGroupVersion.WithResource("supportbundlecollections"),
			v1beta2.SchemeGroupVersion.WithKind("SupportBundleCollection"),
			func() *v1beta2.SupportBundleCollection { return &v1beta2.SupportBundleCollection{} },
			func() *v1beta2.SupportBundleCollectionList { return &v1beta2.SupportBundleCollectionList{} },
			func(dst, src *v1beta2.SupportBundleCollectionList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta2.SupportBundleCollectionList) []*v1beta2.SupportBundleCollection {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta2.SupportBundleCollectionList, items []*v1beta2.SupportBundleCollection) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
