// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "antrea.io/antrea/pkg/apis/controlplane/v1beta2"
	controlplanev1beta2 "antrea.io/antrea/pkg/client/clientset/versioned/typed/controlplane/v1beta2"
	gentype "k8s.io/client-go/gentype"
)

// fakeAppliedToGroups implements AppliedToGroupInterface
type fakeAppliedToGroups struct {
	*gentype.FakeClientWithList[*v1beta2.AppliedToGroup, *v1beta2.AppliedToGroupList]
	Fake *FakeControlplaneV1beta2
}

func newFakeAppliedToGroups(fake *FakeControlplaneV1beta2) controlplanev1beta2.AppliedToGroupInterface {
	return &fakeAppliedToGroups{
		gentype.NewFakeClientWithList[*v1beta2.AppliedToGroup, *v1beta2.AppliedToGroupList](
			fake.Fake,
			"",
			v1beta2.SchemeGroupVersion.WithResource("appliedtogroups"),
			v1beta2.SchemeGroupVersion.WithKind("AppliedToGroup"),
			func() *v1beta2.AppliedToGroup { return &v1beta2.AppliedToGroup{} },
			func() *v1beta2.AppliedToGroupList { return &v1beta2.AppliedToGroupList{} },
			func(dst, src *v1beta2.AppliedToGroupList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta2.AppliedToGroupList) []*v1beta2.AppliedToGroup {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta2.AppliedToGroupList, items []*v1beta2.AppliedToGroup) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
