apiVersion: v1
kind: Service
metadata:
  labels:
    component: antrea-mc-controller
  name: controller-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    component: antrea-mc-controller
