# permissions for end users to edit clusterinfoimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterinfoimport-editor-role
rules:
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - clusterinfoimports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - clusterinfoimports/status
  verbs:
  - get
