# permissions for end users to edit multiclusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterconfig-editor-role
rules:
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - multiclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - multiclusterconfigs/status
  verbs:
  - get
