# permissions for end users to view clusterproperties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterproperty-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multicluster
    app.kubernetes.io/part-of: multicluster
    app.kubernetes.io/managed-by: kustomize
  name: clusterproperty-viewer-role
rules:
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - clusterproperties
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - clusterproperties/status
  verbs:
  - get
