# permissions for end users to edit resourceimportFilters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourceimportfilter-editor-role
rules:
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - resourceimportfilters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - resourceimportfilters/status
  verbs:
  - get
