// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package clusteridentity

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/wait"
	clientset "k8s.io/client-go/kubernetes"
	"k8s.io/klog"
)

const (
	DefaultClusterIdentityConfigMapName = "antrea-cluster-identity"
	uuidConfigMapKey                    = "uuid"
)

// ClusterIdentityAllocator ensures that the antrea-cluster-identity ConfigMap is populated
// correctly, with a valid UUID. It is meant to be used by the Antrea Controller.
type ClusterIdentityAllocator struct {
	clusterIdentityConfigMapNamespace string
	clusterIdentityConfigMapName      string
	k8sClient                         clientset.Interface
}

// NewClusterIdentityAllocator creates a ClusterIdentityAllocator object
func NewClusterIdentityAllocator(
	clusterIdentityConfigMapNamespace string,
	clusterIdentityConfigMapName string,
	k8sClient clientset.Interface,
) *ClusterIdentityAllocator {
	return &ClusterIdentityAllocator{
		clusterIdentityConfigMapNamespace: clusterIdentityConfigMapNamespace,
		clusterIdentityConfigMapName:      clusterIdentityConfigMapName,
		k8sClient:                         k8sClient,
	}
}

func (a *ClusterIdentityAllocator) updateConfigMapIfNeeded() error {
	configMap, err := a.k8sClient.CoreV1().ConfigMaps(a.clusterIdentityConfigMapNamespace).Get(context.TODO(), a.clusterIdentityConfigMapName, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("error when getting '%s/%s' ConfigMap: %v", a.clusterIdentityConfigMapNamespace, a.clusterIdentityConfigMapName, err)
	}

	// returns a triplet consisting of the cluster UUID, a boolean indicating if the UUID needs
	// to be written to the ConfigMap, and an error if applicable
	inspectUUID := func() (uuid.UUID, bool, error) {
		clusterUUIDStr, ok := configMap.Data[uuidConfigMapKey]
		if ok && clusterUUIDStr != "" {
			clusterUUID, err := uuid.Parse(clusterUUIDStr)
			if err != nil {
				return uuid.Nil, false, fmt.Errorf("cluster already has UUID '%s' but it is not valid: %v", clusterUUIDStr, err)
			}
			return clusterUUID, false, nil
		}

		// generate a new random UUID
		clusterUUID := uuid.New()

		return clusterUUID, true, nil
	}

	clusterUUID, clusterUUIDNeedsUpdate, err := inspectUUID()
	if err != nil {
		return err
	}
	if !clusterUUIDNeedsUpdate {
		klog.Infof("Existing cluster UUID: %v", clusterUUID)
		return nil
	}

	configMap.Data = map[string]string{
		uuidConfigMapKey: clusterUUID.String(),
	}
	if _, err := a.k8sClient.CoreV1().ConfigMaps(a.clusterIdentityConfigMapNamespace).Update(context.TODO(), configMap, metav1.UpdateOptions{}); err != nil {
		return fmt.Errorf("error when updating '%s/%s' ConfigMap with new cluster identity: %v", a.clusterIdentityConfigMapNamespace, a.clusterIdentityConfigMapName, err)
	}
	klog.Infof("New cluster UUID: %v", clusterUUID)
	return nil
}

// Run will ensure that the antrea-cluster-identity ConfigMap is up-to-date. It is meant to be
// called asynchronously in its own goroutine, and will keep retrying in case of error, using an
// exponential backoff mechanism.
func (a *ClusterIdentityAllocator) Run(stopCh <-chan struct{}) {
	// exponential backoff, starting at 100ms with a factor of 2. A "steps" value of 10 means we
	// will increase the backoff duration at most 10 times, so the max duration is (100ms * //
	// 2^8), which is about 25s.
	retry := wait.Backoff{
		Steps:    8,
		Duration: 100 * time.Millisecond,
		Factor:   2.0,
		Jitter:   0.0,
	}

	for {
		err := a.updateConfigMapIfNeeded()
		if err == nil {
			return
		}
		sleepDuration := retry.Step()
		klog.Errorf("Cannot validate or update cluster UUID because of the following error, will retry in %v: %v", sleepDuration, err)
		select {
		case <-stopCh:
			return
		case <-time.After(sleepDuration):
			continue
		}
	}
}

// ClusterIdentityProvider is an interface used to retrieve the cluster identity information (UUID),
// as provided by the user or generated by the Antrea Controller.
type ClusterIdentityProvider interface {
	Get() (uuid.UUID, error)
}

type clusterIdentityProvider struct {
	clusterIdentityConfigMapNamespace string
	clusterIdentityConfigMapName      string
	k8sClient                         clientset.Interface
}

// NewClusterIdentityProvider returns a new object implementing the ClusterIdentityProvider
// interface.
func NewClusterIdentityProvider(
	clusterIdentityConfigMapNamespace string,
	clusterIdentityConfigMapName string,
	k8sClient clientset.Interface,
) *clusterIdentityProvider {
	return &clusterIdentityProvider{
		clusterIdentityConfigMapNamespace: clusterIdentityConfigMapNamespace,
		clusterIdentityConfigMapName:      clusterIdentityConfigMapName,
		k8sClient:                         k8sClient,
	}
}

// Get will retrieve the cluster identity (UUID) stored in the antrea-cluster-identity ConfigMap. In
// case of error, clients are invited to retry as the information may not be available yet.
func (p *clusterIdentityProvider) Get() (uuid.UUID, error) {
	configMap, err := p.k8sClient.CoreV1().ConfigMaps(p.clusterIdentityConfigMapNamespace).Get(context.TODO(), p.clusterIdentityConfigMapName, metav1.GetOptions{})
	if err != nil {
		return uuid.Nil, fmt.Errorf("error when getting '%s/%s' ConfigMap: %v", p.clusterIdentityConfigMapNamespace, p.clusterIdentityConfigMapName, err)
	}

	getUUID := func() (uuid.UUID, error) {
		clusterUUIDStr, ok := configMap.Data[uuidConfigMapKey]
		if !ok || clusterUUIDStr == "" {
			return uuid.Nil, fmt.Errorf("cluster UUID has not been set yet")
		}
		clusterUUID, err := uuid.Parse(clusterUUIDStr)
		if err != nil {
			return uuid.Nil, fmt.Errorf("cluster UUID cannot be parsed")
		}
		return clusterUUID, nil
	}

	return getUUID()
}
