apiVersion: multicluster.crd.antrea.io/v1alpha1
kind: ClusterSet
metadata:
  name: test-clusterset
  namespace: kube-system
spec:
  clusterID: test-cluster-member
  leaders:
    - clusterID: test-cluster-leader
      secret: default-member-token
      server: https://<LEADER_APISERVER_IP>:6443
  namespace: antrea-multicluster
