apiVersion: multicluster.crd.antrea.io/v1alpha1
kind: ClusterClaim
metadata:
  name: id.k8s.io
  namespace: kube-system
name: id.k8s.io
value: test-cluster-member
---
apiVersion: multicluster.crd.antrea.io/v1alpha1
kind: ClusterClaim
metadata:
  name: clusterset.k8s.io
  namespace: kube-system
name: clusterset.k8s.io
value: test-clusterset
---
apiVersion: multicluster.crd.antrea.io/v1alpha1
kind: ClusterSet
metadata:
  name: test-clusterset
  namespace: kube-system
spec:
  leaders:
    - clusterID: test-cluster-leader
      secret: leader-access-token
      server: https://<LEADER_CLUSTER_IP>:6443
  members:
    - clusterID: test-cluster-leader
    - clusterID: test-cluster-member
  namespace: antrea-multicluster
