apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: member-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: member-cluster-role
subjects:
- kind: ServiceAccount
  name: member-access-sa
  namespace: antrea-multicluster
