// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterProperties implements ClusterPropertyInterface
type FakeClusterProperties struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var clusterpropertiesResource = schema.GroupVersionResource{Group: "multicluster.crd.antrea.io", Version: "v1alpha1", Resource: "clusterproperties"}

var clusterpropertiesKind = schema.GroupVersionKind{Group: "multicluster.crd.antrea.io", Version: "v1alpha1", Kind: "ClusterProperty"}

// Get takes name of the clusterProperty, and returns the corresponding clusterProperty object, and an error if there is any.
func (c *FakeClusterProperties) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterProperty, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterpropertiesResource, c.ns, name), &v1alpha1.ClusterProperty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProperty), err
}

// List takes label and field selectors, and returns the list of ClusterProperties that match those selectors.
func (c *FakeClusterProperties) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterPropertyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterpropertiesResource, clusterpropertiesKind, c.ns, opts), &v1alpha1.ClusterPropertyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterPropertyList{ListMeta: obj.(*v1alpha1.ClusterPropertyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterPropertyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterProperties.
func (c *FakeClusterProperties) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterpropertiesResource, c.ns, opts))

}

// Create takes the representation of a clusterProperty and creates it.  Returns the server's representation of the clusterProperty, and an error, if there is any.
func (c *FakeClusterProperties) Create(ctx context.Context, clusterProperty *v1alpha1.ClusterProperty, opts v1.CreateOptions) (result *v1alpha1.ClusterProperty, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterpropertiesResource, c.ns, clusterProperty), &v1alpha1.ClusterProperty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProperty), err
}

// Update takes the representation of a clusterProperty and updates it. Returns the server's representation of the clusterProperty, and an error, if there is any.
func (c *FakeClusterProperties) Update(ctx context.Context, clusterProperty *v1alpha1.ClusterProperty, opts v1.UpdateOptions) (result *v1alpha1.ClusterProperty, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterpropertiesResource, c.ns, clusterProperty), &v1alpha1.ClusterProperty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProperty), err
}

// Delete takes name of the clusterProperty and deletes it. Returns an error if one occurs.
func (c *FakeClusterProperties) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clusterpropertiesResource, c.ns, name, opts), &v1alpha1.ClusterProperty{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterProperties) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterpropertiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterPropertyList{})
	return err
}

// Patch applies the patch and returns the patched clusterProperty.
func (c *FakeClusterProperties) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterProperty, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterpropertiesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterProperty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterProperty), err
}
