// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	multiclusterv1alpha1 "antrea.io/antrea/multicluster/pkg/client/clientset/versioned/typed/multicluster/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGateways implements GatewayInterface
type fakeGateways struct {
	*gentype.FakeClientWithList[*v1alpha1.Gateway, *v1alpha1.GatewayList]
	Fake *FakeMulticlusterV1alpha1
}

func newFakeGateways(fake *FakeMulticlusterV1alpha1, namespace string) multiclusterv1alpha1.GatewayInterface {
	return &fakeGateways{
		gentype.NewFakeClientWithList[*v1alpha1.Gateway, *v1alpha1.GatewayList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("gateways"),
			v1alpha1.SchemeGroupVersion.WithKind("Gateway"),
			func() *v1alpha1.Gateway { return &v1alpha1.Gateway{} },
			func() *v1alpha1.GatewayList { return &v1alpha1.GatewayList{} },
			func(dst, src *v1alpha1.GatewayList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GatewayList) []*v1alpha1.Gateway { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.GatewayList, items []*v1alpha1.Gateway) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
