// Copyright 2019 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/vmware-tanzu/antrea/pkg/apis/cleanup/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CleanupStatusLister helps list CleanupStatuses.
type CleanupStatusLister interface {
	// List lists all CleanupStatuses in the indexer.
	List(selector labels.Selector) (ret []*v1beta1.CleanupStatus, err error)
	// Get retrieves the CleanupStatus from the index for a given name.
	Get(name string) (*v1beta1.CleanupStatus, error)
	CleanupStatusListerExpansion
}

// cleanupStatusLister implements the CleanupStatusLister interface.
type cleanupStatusLister struct {
	indexer cache.Indexer
}

// NewCleanupStatusLister returns a new CleanupStatusLister.
func NewCleanupStatusLister(indexer cache.Indexer) CleanupStatusLister {
	return &cleanupStatusLister{indexer: indexer}
}

// List lists all CleanupStatuses in the indexer.
func (s *cleanupStatusLister) List(selector labels.Selector) (ret []*v1beta1.CleanupStatus, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.CleanupStatus))
	})
	return ret, err
}

// Get retrieves the CleanupStatus from the index for a given name.
func (s *cleanupStatusLister) Get(name string) (*v1beta1.CleanupStatus, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("cleanupstatus"), name)
	}
	return obj.(*v1beta1.CleanupStatus), nil
}
