apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    component: antrea-mc-controller
spec:
  selector:
    matchLabels:
      component: antrea-mc-controller
  replicas: 1
  template:
    metadata:
      labels:
        component: antrea-mc-controller
      annotations:
        checksum/config: checksum-placeholder
    spec:
      hostNetwork: true
      containers:
      - command:
        image: antrea/antrea-mc-controller:latest
        imagePullPolicy: IfNotPresent
        name: antrea-mc-controller
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
      serviceAccountName: controller
      terminationGracePeriodSeconds: 10
