apiVersion: batch/v1
kind: Job
metadata:
  name: cyclonus
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - ./cyclonus
        - generate
        - --mode=upstream
        - --noisy=true
        - --perturbation-wait-seconds=15
        - --cleanup-namespaces=true
        name: cyclonus
        imagePullPolicy: Always
        image: mfenwick100/cyclonus:latest
      serviceAccount: cyclonus
