// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	"time"

	v1beta2 "github.com/vmware-tanzu/antrea/pkg/apis/controlplane/v1beta2"
	scheme "github.com/vmware-tanzu/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EgressGroupsGetter has a method to return a EgressGroupInterface.
// A group's client should implement this interface.
type EgressGroupsGetter interface {
	EgressGroups() EgressGroupInterface
}

// EgressGroupInterface has methods to work with EgressGroup resources.
type EgressGroupInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.EgressGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.EgressGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	EgressGroupExpansion
}

// egressGroups implements EgressGroupInterface
type egressGroups struct {
	client rest.Interface
}

// newEgressGroups returns a EgressGroups
func newEgressGroups(c *ControlplaneV1beta2Client) *egressGroups {
	return &egressGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the egressGroup, and returns the corresponding egressGroup object, and an error if there is any.
func (c *egressGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.EgressGroup, err error) {
	result = &v1beta2.EgressGroup{}
	err = c.client.Get().
		Resource("egressgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressGroups that match those selectors.
func (c *egressGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.EgressGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.EgressGroupList{}
	err = c.client.Get().
		Resource("egressgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressGroups.
func (c *egressGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("egressgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}
