apiVersion: v1
kind: ConfigMap
metadata:
  name: dhcp-server-conf
  namespace: kube-system
  labels:
    environment: antrea-multus-demo
data:
  dhcpd.conf: |
    subnet 192.168.78.0 netmask 255.255.255.0 {
      range 192.168.78.200 192.168.78.250;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: dhcp-server
  labels:
    environment: antrea-multus-demo
    app: dhcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: antrea-multus-demo
      app: dhcp-server
  template:
    metadata:
      labels:
        environment: antrea-multus-demo
        app: dhcp-server
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: wait-for-interface
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh"]
        args: ["-c", "while ! ip link show mac0 | grep -q ',UP,'; do echo 'Waiting for mac0'; sleep 1; done"]
      containers:
      - name: dhcp-server
        image: networkboot/dhcpd:latest
        imagePullPolicy: IfNotPresent
        args: ["mac0"]
        volumeMounts:
        - mountPath: /data/dhcpd.conf
          name: dhcp-server-conf
          readOnly: true
          subPath: dhcpd.conf
      volumes:
      - configMap:
          name: dhcp-server-conf
        name: dhcp-server-conf
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
