apiVersion: "crd.antrea.io/v1beta1"
kind: IPPool
metadata:
  name: macvlan-ippool
spec:
  ipRanges:
  - start: "192.168.78.200"
    end: "192.168.78.250"
  subnetInfo:
    gateway: "192.168.78.1"
    prefixLength: 24
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp0s9",
      "mode": "bridge",
      "ipam": {
        "type": "antrea",
        "ippools" [ "macvlan-ippool" ]
      }
    }'
