// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/apis/flow/v1alpha1/service.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*Flow                `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_pkg_apis_flow_v1alpha1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_flow_v1alpha1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_flow_v1alpha1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_pkg_apis_flow_v1alpha1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_flow_v1alpha1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_flow_v1alpha1_service_proto_rawDescGZIP(), []int{1}
}

var File_pkg_apis_flow_v1alpha1_service_proto protoreflect.FileDescriptor

const file_pkg_apis_flow_v1alpha1_service_proto_rawDesc = "" +
	"\n" +
	"$pkg/apis/flow/v1alpha1/service.proto\x12'antrea_io.antrea.pkg.apis.flow.v1alpha1\x1a!pkg/apis/flow/v1alpha1/flow.proto\"T\n" +
	"\rExportRequest\x12C\n" +
	"\x05flows\x18\x01 \x03(\v2-.antrea_io.antrea.pkg.apis.flow.v1alpha1.FlowR\x05flows\"\x10\n" +
	"\x0eExportResponse2\x90\x01\n" +
	"\x11FlowExportService\x12{\n" +
	"\x06Export\x126.antrea_io.antrea.pkg.apis.flow.v1alpha1.ExportRequest\x1a7.antrea_io.antrea.pkg.apis.flow.v1alpha1.ExportResponse(\x01B\x18Z\x16pkg/apis/flow/v1alpha1b\x06proto3"

var (
	file_pkg_apis_flow_v1alpha1_service_proto_rawDescOnce sync.Once
	file_pkg_apis_flow_v1alpha1_service_proto_rawDescData []byte
)

func file_pkg_apis_flow_v1alpha1_service_proto_rawDescGZIP() []byte {
	file_pkg_apis_flow_v1alpha1_service_proto_rawDescOnce.Do(func() {
		file_pkg_apis_flow_v1alpha1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apis_flow_v1alpha1_service_proto_rawDesc), len(file_pkg_apis_flow_v1alpha1_service_proto_rawDesc)))
	})
	return file_pkg_apis_flow_v1alpha1_service_proto_rawDescData
}

var file_pkg_apis_flow_v1alpha1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_apis_flow_v1alpha1_service_proto_goTypes = []any{
	(*ExportRequest)(nil),  // 0: antrea_io.antrea.pkg.apis.flow.v1alpha1.ExportRequest
	(*ExportResponse)(nil), // 1: antrea_io.antrea.pkg.apis.flow.v1alpha1.ExportResponse
	(*Flow)(nil),           // 2: antrea_io.antrea.pkg.apis.flow.v1alpha1.Flow
}
var file_pkg_apis_flow_v1alpha1_service_proto_depIdxs = []int32{
	2, // 0: antrea_io.antrea.pkg.apis.flow.v1alpha1.ExportRequest.flows:type_name -> antrea_io.antrea.pkg.apis.flow.v1alpha1.Flow
	0, // 1: antrea_io.antrea.pkg.apis.flow.v1alpha1.FlowExportService.Export:input_type -> antrea_io.antrea.pkg.apis.flow.v1alpha1.ExportRequest
	1, // 2: antrea_io.antrea.pkg.apis.flow.v1alpha1.FlowExportService.Export:output_type -> antrea_io.antrea.pkg.apis.flow.v1alpha1.ExportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_apis_flow_v1alpha1_service_proto_init() }
func file_pkg_apis_flow_v1alpha1_service_proto_init() {
	if File_pkg_apis_flow_v1alpha1_service_proto != nil {
		return
	}
	file_pkg_apis_flow_v1alpha1_flow_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_flow_v1alpha1_service_proto_rawDesc), len(file_pkg_apis_flow_v1alpha1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_flow_v1alpha1_service_proto_goTypes,
		DependencyIndexes: file_pkg_apis_flow_v1alpha1_service_proto_depIdxs,
		MessageInfos:      file_pkg_apis_flow_v1alpha1_service_proto_msgTypes,
	}.Build()
	File_pkg_apis_flow_v1alpha1_service_proto = out.File
	file_pkg_apis_flow_v1alpha1_service_proto_goTypes = nil
	file_pkg_apis_flow_v1alpha1_service_proto_depIdxs = nil
}
