// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	multiclusterv1alpha1 "antrea.io/antrea/v2/multicluster/apis/multicluster/v1alpha1"
	scheme "antrea.io/antrea/v2/multicluster/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MemberClusterAnnouncesGetter has a method to return a MemberClusterAnnounceInterface.
// A group's client should implement this interface.
type MemberClusterAnnouncesGetter interface {
	MemberClusterAnnounces(namespace string) MemberClusterAnnounceInterface
}

// MemberClusterAnnounceInterface has methods to work with MemberClusterAnnounce resources.
type MemberClusterAnnounceInterface interface {
	Create(ctx context.Context, memberClusterAnnounce *multiclusterv1alpha1.MemberClusterAnnounce, opts v1.CreateOptions) (*multiclusterv1alpha1.MemberClusterAnnounce, error)
	Update(ctx context.Context, memberClusterAnnounce *multiclusterv1alpha1.MemberClusterAnnounce, opts v1.UpdateOptions) (*multiclusterv1alpha1.MemberClusterAnnounce, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*multiclusterv1alpha1.MemberClusterAnnounce, error)
	List(ctx context.Context, opts v1.ListOptions) (*multiclusterv1alpha1.MemberClusterAnnounceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *multiclusterv1alpha1.MemberClusterAnnounce, err error)
	MemberClusterAnnounceExpansion
}

// memberClusterAnnounces implements MemberClusterAnnounceInterface
type memberClusterAnnounces struct {
	*gentype.ClientWithList[*multiclusterv1alpha1.MemberClusterAnnounce, *multiclusterv1alpha1.MemberClusterAnnounceList]
}

// newMemberClusterAnnounces returns a MemberClusterAnnounces
func newMemberClusterAnnounces(c *MulticlusterV1alpha1Client, namespace string) *memberClusterAnnounces {
	return &memberClusterAnnounces{
		gentype.NewClientWithList[*multiclusterv1alpha1.MemberClusterAnnounce, *multiclusterv1alpha1.MemberClusterAnnounceList](
			"memberclusterannounces",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *multiclusterv1alpha1.MemberClusterAnnounce {
				return &multiclusterv1alpha1.MemberClusterAnnounce{}
			},
			func() *multiclusterv1alpha1.MemberClusterAnnounceList {
				return &multiclusterv1alpha1.MemberClusterAnnounceList{}
			},
		),
	}
}
