// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AccountNodeMappingListerExpansion allows custom methods to be added to
// AccountNodeMappingLister.
type AccountNodeMappingListerExpansion interface{}

// AccountNodeMappingNamespaceListerExpansion allows custom methods to be added to
// AccountNodeMappingNamespaceLister.
type AccountNodeMappingNamespaceListerExpansion interface{}

// ClusterNetworkPolicyListerExpansion allows custom methods to be added to
// ClusterNetworkPolicyLister.
type ClusterNetworkPolicyListerExpansion interface{}

// NetworkPolicyListerExpansion allows custom methods to be added to
// NetworkPolicyLister.
type NetworkPolicyListerExpansion interface{}

// NetworkPolicyNamespaceListerExpansion allows custom methods to be added to
// NetworkPolicyNamespaceLister.
type NetworkPolicyNamespaceListerExpansion interface{}

// TierListerExpansion allows custom methods to be added to
// TierLister.
type TierListerExpansion interface{}

// TraceflowListerExpansion allows custom methods to be added to
// TraceflowLister.
type TraceflowListerExpansion interface{}
