// Copyright 2025 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	crdv1alpha1 "antrea.io/antrea/pkg/apis/crd/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FlowExporterTargetLister helps list FlowExporterTargets.
// All objects returned here must be treated as read-only.
type FlowExporterTargetLister interface {
	// List lists all FlowExporterTargets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*crdv1alpha1.FlowExporterTarget, err error)
	// Get retrieves the FlowExporterTarget from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*crdv1alpha1.FlowExporterTarget, error)
	FlowExporterTargetListerExpansion
}

// flowExporterTargetLister implements the FlowExporterTargetLister interface.
type flowExporterTargetLister struct {
	listers.ResourceIndexer[*crdv1alpha1.FlowExporterTarget]
}

// NewFlowExporterTargetLister returns a new FlowExporterTargetLister.
func NewFlowExporterTargetLister(indexer cache.Indexer) FlowExporterTargetLister {
	return &flowExporterTargetLister{listers.New[*crdv1alpha1.FlowExporterTarget](indexer, crdv1alpha1.Resource("flowexportertarget"))}
}
