// Copyright 2024 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "antrea.io/antrea/pkg/apis/crd/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// ClusterNetworkPolicyLister helps list ClusterNetworkPolicies.
// All objects returned here must be treated as read-only.
type ClusterNetworkPolicyLister interface {
	// List lists all ClusterNetworkPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ClusterNetworkPolicy, err error)
	// Get retrieves the ClusterNetworkPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.ClusterNetworkPolicy, error)
	ClusterNetworkPolicyListerExpansion
}

// clusterNetworkPolicyLister implements the ClusterNetworkPolicyLister interface.
type clusterNetworkPolicyLister struct {
	listers.ResourceIndexer[*v1beta1.ClusterNetworkPolicy]
}

// NewClusterNetworkPolicyLister returns a new ClusterNetworkPolicyLister.
func NewClusterNetworkPolicyLister(indexer cache.Indexer) ClusterNetworkPolicyLister {
	return &clusterNetworkPolicyLister{listers.New[*v1beta1.ClusterNetworkPolicy](indexer, v1beta1.Resource("clusternetworkpolicy"))}
}
