name: Golicense
on:
  pull_request:
    branches:
    - main
    - release-*
    - feature/*
  push:
    branches:
    - main
    - release-*
    - feature/*
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        show-progress: false
    - uses: antrea-io/has-changes@8af46c0ea505faf5c57d655802471141dc1ecc26 # v2.3.0
      id: check_diff
      with:
        paths-ignore: docs/* ci/jenkins/* *.md hack/.notableofcontents
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  golicense:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' || github.event_name != 'pull_request' }}
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        show-progress: false
    - name: Set up Go using version from .go-version
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: '.go-version'
    - name: Cache licensing information for dependencies
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: cache
      env:
        cache-name: cache-lichen-deps-licensing-info
      with:
        path: license-reports
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum', 'ci/golicense/**') }}
    - run: mkdir antrea-bins
    - name: Build assets
      run: |
        export VERSION="$(head VERSION)"
        ./hack/release/prepare-assets.sh ./antrea-bins
    - name: Build Linux binaries
      run: BINDIR=./antrea-bins make bin
    - name: Run lichen
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir license-reports
        ./ci/golicense/run.sh ./antrea-bins ./license-reports
    - name: Upload licensing information
      if: ${{ always() }}
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: licenses.deps
        path: license-reports/ALL.deps.txt
        retention-days: 90 # max value
