name: Integration
on:
  pull_request:
    branches:
    - master
    - release-*
    - ipv6
  push:
    branches:
    - master
    - release-*
    - ipv6
jobs:
  test-integration:
    name: Integration tests
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Run integration tests
      run: make docker-test-integration
