name: Integration

on: [push]

jobs:
  integration:

    runs-on: [ubuntu-18.04]

    steps:
    - name: Check out code
      uses: actions/checkout@v1
      
    - name: Run integration test
      run: make test-integration
