name: Status

on:
  pull_request_review_comment:
    types: [created, deleted]

permissions:
  statuses: write

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: Skip tests
    runs-on: ubuntu-latest

    steps:
      - name: Create status
        run: |
          echo hello
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.STATUS_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "success",
            "context": "jenkins-conformance",
            "description": "Skipped",
            "target_url": "https://github.com/antrea-io/antrea"
            }'
